### ISSUE TITLE
Staging Directory needs to not use tempfile

### ISSUE THREAD

**Issue by MrGiga** [Tripwire/ansible-te_axon#1]
install.yml has the following:

```
- name: Create staging path
  tempfile:
    state: directory
    suffix: te_axon
  register: staging
```

This should be using the remote_tmp set in ansible configuration file. My machines doesn't allow execution in /tmp for security purposes, so this task is broken for me
